### ISSUE TITLE
Is it possible to configure this to only use some rules?

### ISSUE THREAD

**Issue by enumag** [ergebnis/phpstan-rules#522] opened 2023-03-27 06:20 UTC
I'd like to use some of the rules from this package. However some other rules are a bit too much. Is it possible to configure this to only use some of the rules but not all of them?

For instance I want to avoid the declare strict rule because that's already taken care of by my very strict coding standard and it's entirely unnecessary to make the already slow phpstan pipeline even slower by double checking it. And while I do agree with most of the rules, a few of them (especially those regarding nullable types) might be a bit too aggressive.

Note that I'm using `phpstan/extension-installer` so it isn't an option to avoid including your configuration and only copy some parts of it manually.

I'm using most of the rules from https://github.com/shipmonk-rnd/phpstan-rules for instance but it very easily allows me to disable some of them. Something like that would be ideal.

**Comment by localheinz** [comment] 2023-05-01 09:43
Duplicate of #518

**Closed by localheinz** 2023-05-01 09:43 UTC
Labels: enhancement
